package com.luretechnologies.tms.ui.view.admin.user;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserAdminViewDesign extends Panel {
	protected HorizontalSplitPanel splitscreen;
	protected VerticalLayout userdatalayout;
	protected Label userLabel;
	protected HorizontalLayout saveCancelLayout;
	protected Button save;
	protected Button cancel;
	protected FormLayout form;
	protected TextField name;
	protected ComboBox<java.lang.String> roles;
	protected TextField firstname;
	protected TextField lastname;
	protected TextField email;
	protected HorizontalLayout authenticationLayout;
	protected Label authenticationLabel;
	protected Button anuthenticationButton;
	protected HorizontalLayout activeLayout;
	protected Label activelabel;
	protected CheckBox active;
	protected HorizontalLayout fixedIPLayout;
	protected Label fixediplabel;
	protected CheckBox fixedip;
	protected TextField ipField;
	protected HorizontalLayout passfrequencyLayout;
	protected Label passfrequencyLabel;
	protected ComboBox<java.lang.Integer> passwordFrequency;
	protected Button temppassowrd;
	protected ComboBox<java.lang.String> verificationFrequency;
	protected TextField password;
	protected HorizontalLayout buttonsLayout;
	protected HorizontalLayout searchBarLayout;
	protected CssLayout userSearchLayout;
	protected TextField search;
	protected Button add;
	protected Button edit;
	protected Button delete;
	protected HorizontalLayout screen;
	protected Grid<com.luretechnologies.tms.backend.data.entity.User> list;

	public UserAdminViewDesign() {
		Design.read(this);
	}
}
