/**
 * COPYRIGHT @ Lure Technologies, LLC.
 * ALL RIGHTS RESERVED
 *
 * Developed by Lure Technologies, LLC. (www.luretechnologies.com)
 *
 * Copyright in the whole and every part of this software program belongs to
 * Lure Technologies, LLC (“Lure”).  It may not be used, sold, licensed,
 * transferred, copied or reproduced in whole or in part in any manner or
 * form other than in accordance with and subject to the terms of a written
 * license from Lure or with the prior written consent of Lure or as
 * permitted by applicable law.
 *
 * This software program contains confidential and proprietary information and
 * must not be disclosed, in whole or in part, to any person or organization
 * without the prior written consent of Lure.  If you are neither the
 * intended recipient, nor an agent, employee, nor independent contractor
 * responsible for delivering this message to the intended recipient, you are
 * prohibited from copying, disclosing, distributing, disseminating, and/or
 * using the information in this email in any manner. If you have received
 * this message in error, please advise us immediately at
 * legal@luretechnologies.com by return email and then delete the message from your
 * computer and all other records (whether electronic, hard copy, or
 * otherwise).
 *
 * Any copies or reproductions of this software program (in whole or in part)
 * made by any method must also include a copy of this legend.
 *
 * Inquiries should be made to legal@luretechnologies.com
 *
 */
package com.luretechnologies.server.data.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.luretechnologies.common.enums.PermissionEnum;
import com.luretechnologies.common.validator.RegExp;
import com.luretechnologies.server.common.Messages;
import com.luretechnologies.server.constraints.FieldNotBlank;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import org.hibernate.annotations.Type;

/**
 * Stores roles.
 */
@Entity
@Table(name = "Role")
//@JsonIgnoreProperties(ignoreUnknown=true)
public class Role implements Serializable {

    public final static String SUPER_ADMIN = "SUPER_ADMIN";
    
    /**
     *
     */
    public Role() {
    }

    @Column(name = "id", nullable = false, length = 20)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(value = "The database identification.")
    private long id;

    @NotNull(message = Messages.VALUE_IS_EMPTY)
    @FieldNotBlank
    @Size(max = 100, message = Messages.INVALID_DATA_LENGHT)
    @Pattern(regexp = RegExp.EXP_REG_VALID_ALPHANUMERIC_SPECIAL_NAME, message = Messages.INVALID_DATA_ENTRY)
    @Column(name = "name", nullable = false, unique = true, length = 100)
    @ApiModelProperty(value = "The name.", required = true)
    private String name;

    @Size(max = 255, message = Messages.INVALID_DATA_LENGHT)
    @Pattern(regexp = RegExp.EXP_REG_VALID_ALPHANUMERIC_SPECIAL_DESC, message = Messages.INVALID_DATA_ENTRY)
    @Column(name = "description", nullable = true, length = 255)
    @ApiModelProperty(value = "The description.")
    private String description;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "Role_Permission", joinColumns = {
        @JoinColumn(name = "role")})
    @Column(name = "permission", nullable = true, length = 2)
    @Type(type = "com.luretechnologies.server.hibernate.enums.PermissionUserType")
    @ApiModelProperty(value = "The permissions.")
    private Set<PermissionEnum> permissions = new HashSet<>();

//    This is the original mapping generated by Visual Paradigm - We used the above to simplify
//      @OneToMany(mappedBy="role", targetEntity=com.luretechnologies.server.data.model.RolePermission.class)	
//	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE, org.hibernate.annotations.CascadeType.LOCK})	
//	@org.hibernate.annotations.LazyCollection(org.hibernate.annotations.LazyCollectionOption.TRUE)	
//	private java.util.Set<com.luretechnologies.server.data.model.RolePermission> rolePermission = new java.util.HashSet<com.luretechnologies.server.data.model.RolePermission>();
    @OneToMany(mappedBy = "role", targetEntity = User.class, fetch = FetchType.LAZY)
    @ApiModelProperty(value = "The users.")
    private Set<User> users = new HashSet<>();

    /**
     * Database identification.
     */
    private void setId(long value) {
        this.id = value;
    }

    /**
     * Database identification.
     *
     * @return
     */
    public long getId() {
        return id;
    }

    /**
     * Role's name.
     *
     * @param value
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Role's name.
     *
     * @return
     */
    public String getName() {
        return name;
    }

    /**
     * Role's description.
     *
     * @param value
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Role's description.
     *
     * @return
     */
    public String getDescription() {
        return description;
    }

    /**
     *
     * @param value
     */
    public void setUsers(Set<User> value) {
        this.users = value;
    }

    /**
     *
     * @return
     */
    @JsonIgnore
    public Set<User> getUsers() {
        return users;
    }

    /**
     *
     * @return
     */
    public Set<PermissionEnum> getPermissions() {
        return permissions;
    }

    /**
     *
     * @param permissions
     */
    public void setPermissions(Set<PermissionEnum> permissions) {
        this.permissions = permissions;
    }

    @Override
    public String toString() {
        return String.valueOf(getId());
    }

}
